modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="buildyourhome__uncreative_people"
version="1.0.0"
displayName="BuildYourHome 4 uncreative people"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kimpa, MCreator"

[[dependencies.buildyourhome__uncreative_people]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




